/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as appEventsIndexImport } from './routes/(app)/events/index'
import { Route as appEventsEventIdImport } from './routes/(app)/events/$eventId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const appEventsIndexRoute = appEventsIndexImport.update({
  id: '/(app)/events/',
  path: '/events/',
  getParentRoute: () => rootRoute,
} as any)

const appEventsEventIdRoute = appEventsEventIdImport.update({
  id: '/(app)/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(app)/events/$eventId': {
      id: '/(app)/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof appEventsEventIdImport
      parentRoute: typeof rootRoute
    }
    '/(app)/events/': {
      id: '/(app)/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof appEventsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/$eventId': typeof appEventsEventIdRoute
  '/events': typeof appEventsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/$eventId': typeof appEventsEventIdRoute
  '/events': typeof appEventsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(app)/events/$eventId': typeof appEventsEventIdRoute
  '/(app)/events/': typeof appEventsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/events/$eventId' | '/events'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events/$eventId' | '/events'
  id: '__root__' | '/' | '/(app)/events/$eventId' | '/(app)/events/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appEventsEventIdRoute: typeof appEventsEventIdRoute
  appEventsIndexRoute: typeof appEventsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appEventsEventIdRoute: appEventsEventIdRoute,
  appEventsIndexRoute: appEventsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(app)/events/$eventId",
        "/(app)/events/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(app)/events/$eventId": {
      "filePath": "(app)/events/$eventId.tsx"
    },
    "/(app)/events/": {
      "filePath": "(app)/events/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
